language: java
addons:
  sonarcloud:
    organization: "tizianotaglienti"
    token:
      secure: "QLhniTBvhpM0HwF7d0onHEB6qyyjqTyGFXTw62JeKmS+Ydecnrv5+4VMbzbBj+Av3ZlwJnoLc9WH0pRI0Yihg6f3EsheyyGLyAjuVmRqGtDT1Qe+eNbZ1Cq6KjM3isV5uwLUfyQnLW6DK5JuKAW7RKe7suJpgB8+0o1oTmEjxMith9lWqQJ38fp8fi5QS31JIqK0yIu7Un7cFgr1kHIYlKQ6bCS+vvHE2mGUbGQKDzclh+zS3aUi0ThTFkyV5N/ZYHyWX5eDx+XMs6r2mNzKvAD4ULsBDgLeUjtDlhrcQsVKj/6/gcDk2Palozd/Zu8YRNdmuTChfoUa5H7e/+2fr6N2bWuvXPZR1V8Gpr1W/al5LH13n4suws5Br0YoszG3gSEpIGppbFlroGSSgrpHYrgM5Qorly7sD5SqQ9RTHAGY2XFUEfOYzI4CTSlhWAvd1vwemzARovnCXFUMw9NECvAwuyw8p1Pqimv57YcCM7VnL7wWDNg+xo3jnUUDoJPX+bf7geoebW4t5/07oUGAiVs2blQ+lBMMhPv4cGZY3LI7W9nXL+1SxqotIbu3y6b7L5GFgdcNXrGAqZyx3zvF1K3Gfb/bbqV29hc5Kkdm1o8XbrqSjDsZzDWuNJzrBPWdrKOeqLLAO99iKEEjnaJYIDR7rGt+UStnBL70rujR9/s="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=tizianotaglienti_storm