language: java
addons:
  sonarcloud:
    organization: "tizianotaglienti"
    token:
      secure: "m2VCxgELdOuB60MgtZHeo9+cQW/GHDIGHUbIGS7Lpu9kbn5uZLmRC/RyYQqTSM9gs+FBnjbyt+YSltw/jcKl2L/BmFKVbGJ+aouomrwL70CdNo3XDBE9vTiREObap/smIoqCxYAWdqzuBAd9zIZGWlxABb0uzEkHm2c1rtHjiyjDPJyqXvPT/mQBzDQaIHxLbb46IFWjj3OYav6JIDk6OFXzkp8hvyyipYNWO8qjyJ3btlvSncw+pmyDCKuMb14ExQxljFHpMSYSUJ+EhVm1t+FIKUEcdNnLe4JNEZZsNwGa+6tPBXgtoeK00MswXukr+7cYLKtMU4Jwh+1Tf1g9O9XAzBw9Js2rwJf5HblvQNl04YQz2pDoCU9oEb7lc+tMlEU9ychUvBXTocZrMZRsy4CmVPiyms3UHTaUySDo0UPfj+sdwXj/Zu0uXNIGmeA4XuKUADfIwduzFR/wibawqC5bptBfPwLpL1HZA6t/xNaerkGSR3pNe0f31yBMtVMOGJXDlKLMEJS24k1Fz8jADvKx3eMbTPfIAaMa24B1Kkrwi+IA3zCTTMMeWsoIzCxbEXd09WluRvREob85pkk1sYCYFuddLGFgCQWmBuApL/ZNHK5G4on2lGalwzEtsHrj9QBKLwNupXvtA4H6GprF5KF//2oraGauUVrmivaiJ7k="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar